### ISSUE TITLE
no way

### ISSUE THREAD

**Issue by funnius** [WalmartSolutions/skidfuscator-src#1]
good luck not getting dmca'd 🙏

**Comment by ethaanol** [comment]
![IMG_3549](https://github.com/WalmartSolutions/skidfuscator-src/assets/142350050/a9bbf9e6-4d1c-4f7a-ab1b-5eb1c01bd82d)

**Comment by funnius** [comment]
> ![IMG_3549](https://private-user-images.githubusercontent.com/142350050/319147768-a9bbf9e6-4d1c-4f7a-ab1b-5eb1c01bd82d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDExMDIsIm5iZiI6MTcxMjE0MDgwMiwicGF0aCI6Ii8xNDIzNTAwNTAvMzE5MTQ3NzY4LWE5YmJmOWU2LTRkMWMtNGY3YS1hYjFiLTVlYjFjMDFiZDgyZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QxMDQwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjMwN2I4M2Q4Y2MwNTg0ZjgxNjQ5MTVjNzk1ZjI1MmZmYmE5OGMwYWRhMWVjNGNhYjA3MjA1ZDEwMjNlYzE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S2Py4GafAKwVnZ-z-PVf7w-HS8tSKbr7DRfzawhLm3E)

ah hell naw i just got mogged 😭
